stages:
    - build
    - cleanup_build
    - test
    
build_job:
    stage: build
    tags: # build gitRunner的tag标签
        - build
    script:
        - ./build/ci.sh

cleanup_build_job:
    stage: cleanup_build
    tags: # build gitRunner的tag标签
        - build
    script:
        - echo "cleanup_build_job"

test_job:
    stage: test
    tags: # build gitRunner的tag标签
        - build
    script:
        - pwd
        - docker -v
    # - python manage.py runserver 0.0.0.0:8000